//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEAutoInvite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEAutoInvite.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EvE-AutoInvite.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved-Characters.json.
        /// </summary>
        internal static string AuthBackupFile {
            get {
                return ResourceManager.GetString("AuthBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c12e53149ed74c23ae56f6d442c8105a.
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://127.0.0.1:2317/eve-auto-fleet/.
        /// </summary>
        internal static string EndpointCallbackURL {
            get {
                return ResourceManager.GetString("EndpointCallbackURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/v2/oauth/authorize/.
        /// </summary>
        internal static string EndpointOAuthAuthorize {
            get {
                return ResourceManager.GetString("EndpointOAuthAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/.well-known/oauth-authorization-server.
        /// </summary>
        internal static string EndPointOAuthMetaData {
            get {
                return ResourceManager.GetString("EndPointOAuthMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/v2/oauth/token/.
        /// </summary>
        internal static string EndpointOAuthToken {
            get {
                return ResourceManager.GetString("EndpointOAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/oauth/verify.
        /// </summary>
        internal static string EndpointOAuthVerify {
            get {
                return ResourceManager.GetString("EndpointOAuthVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to esi-fleets.read_fleet.v1 esi-fleets.write_fleet.v1.
        /// </summary>
        internal static string ESIScopes {
            get {
                return ResourceManager.GetString("ESIScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS256.
        /// </summary>
        internal static string JWKAlgorithm {
            get {
                return ResourceManager.GetString("JWKAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVE Online.
        /// </summary>
        internal static string JWKAudience {
            get {
                return ResourceManager.GetString("JWKAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.eveonline.com.
        /// </summary>
        internal static string JWKIssuersHost {
            get {
                return ResourceManager.GetString("JWKIssuersHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com.
        /// </summary>
        internal static string JWKIssuersURI {
            get {
                return ResourceManager.GetString("JWKIssuersURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVE-AUTOINVITE.
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
