name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        run: |
          # Download and install the .NET Framework 4.8 SDK
          wget https://download.visualstudio.microsoft.com/download/pr/61670714-9a31-4f4f-ba16-fee52d81f7f0/f0ad32eef9a93bc0dcf889c7b5d0d956/ndp48-x86-x64-allos-enu.exe -OutFile dotnet-framework-installer.exe
          Start-Process -Wait -FilePath dotnet-framework-installer.exe -ArgumentList "/quiet /norestart"

      - name: Restore dependencies and build
        run: |
          nuget restore YourSolutionFile.sln
          msbuild /p:Configuration=Release YourSolutionFile.sln

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ''
          body: |
            $(git log -1 --pretty=format:"%s%n%n%b")
          tag_name: v${{ github.run_number }}
          title: Release ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
