name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download .NET Framework SDK
        run: |
          Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/714a99a2-db28-432e-9a39-4345ba11e73f/5108686aec021898cec3de2cc4d9fd3c/ndp48-devpack-enu.exe" -OutFile "dotnet-framework-installer.exe"

      - name: Install .NET Framework SDK
        run: |
          Start-Process -Wait -FilePath "dotnet-framework-installer.exe" -ArgumentList "/quiet /norestart"

      - name: Restore dependencies and build
        run: |
          nuget restore EVE-AutoInvite.sln
          msbuild /p:Configuration=Release EVE-AutoInvite.sln

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ''
          body: |
            $(git log -1 --pretty=format:"%s%n%n%b")
          tag_name: v${{ github.run_number }}
          title: Release ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
